version: "3.8"

services:
  redis-stack:
    image: redis/redis-stack:latest
    container_name: depinder-redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - depinder_redis_data:/data
    networks:
      - traefiknet
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik on itself to view dashboard and assign subdomain to view it
      - "traefik.http.routers.redis.rule=Host(`depinder.redisinsight.localhost`)" # <== Setting the domain for the dashboard
      - "traefik.http.routers.redis.service=redis" # <== Enabling the api to be a service to access
      - "traefik.http.services.redis.loadbalancer.server.port=8001" # <== Enabling the api to be a service to access
      - "traefik.docker.network=traefiknet"
      - "traefik.http.routers.redis.tls=true"
      - "traefik.http.routers.redis.tls.certresolver=default"

volumes:
  depinder_redis_data:

networks:
  traefiknet:
    external: true

